#
# Makefile for the linux kernel.
#

obj-y							+= iphone.o irq.o timer.o power.o clock.o dma.o gpio.o i2c.o spi.o usb.o vfl.o ftl.o nand.o

obj-$(CONFIG_IPHONE_PMU)		+= pmu.o
obj-$(CONFIG_IPHONE_BATTERY)	+= iphone_battery.o
obj-$(CONFIG_IPHONE_BACKLIGHT)	+= iphone_bl.o
